#!/bin/bash

# SSL Monitor Pro - Cloudflare Pages Setup for GitLab Migration
# Usage: ./scripts/setup-cloudflare.sh

echo "☁️  Configuring Cloudflare Pages for GitLab Migration..."
echo "====================================================="

# Load secrets
if [ -f ".migration-secrets" ]; then
    source .migration-secrets
else
    echo "❌ Error: .migration-secrets file not found!"
    exit 1
fi

echo ""
echo "📋 Current Cloudflare Pages Configuration:"
echo "   • Project: ssl-monitor-pro"
echo "   • URL: https://cloudsre.xyz"
echo "   • Current Source: GitHub (root/ssl-monitor-pro)"
echo "   • Target Source: GitLab (root/ssl-monitor-pro)"
echo ""

echo "🔧 Configuration Options:"
echo ""
echo "1️⃣ Option A: Direct GitLab Integration (Recommended)"
echo "   • Connect Cloudflare Pages directly to GitLab"
echo "   • Automatic builds on every push"
echo "   • Built-in preview deployments"
echo ""
echo "2️⃣ Option B: GitLab CI/CD Upload (Current Setup)"
echo "   • Use Wrangler CLI from GitLab pipeline"
echo "   • Manual control over build process"
echo "   • Custom build commands"
echo ""

echo "🚀 Recommended: Option A - Direct GitLab Integration"
echo ""
echo "📋 Manual Configuration Steps:"
echo ""
echo "1️⃣ Cloudflare Dashboard Setup:"
echo "   • Go to: https://dash.cloudflare.com"
echo "   • Navigate to: Pages → ssl-monitor-pro"
echo "   • Go to: Settings → Build & Deploy"
echo ""
echo "2️⃣ Disconnect Current Source:"
echo "   • Click: 'Disconnect' next to GitHub"
echo "   • Confirm disconnection"
echo ""
echo "3️⃣ Connect to GitLab:"
echo "   • Click: 'Connect to Git'"
echo "   • Select: GitLab"
echo "   • Repository: root/ssl-monitor-pro"
echo "   • Branch: main"
echo ""
echo "4️⃣ Build Configuration:"
echo "   • Build command: npm run build"
echo "   • Build output directory: frontend-modern/dist"
echo "   • Root directory: frontend-modern"
echo "   • Environment variables: (if needed)"
echo ""
echo "5️⃣ Custom Domain:"
echo "   • Ensure cloudsre.xyz is still connected"
echo "   • SSL/TLS: Full (strict)"
echo ""

echo "🔧 Alternative: Option B - GitLab CI/CD Upload"
echo ""
echo "📋 Current GitLab CI/CD Configuration:"
echo "   • Uses Wrangler CLI"
echo "   • API Token: Already in GitLab Variables"
echo "   • Project Name: ssl-monitor-pro"
echo ""
echo "📝 GitLab CI/CD Job (already configured):"
echo "   deploy-frontend:"
echo "     stage: deploy"
echo "     image: node:18-alpine"
echo "     before_script:"
echo "       - npm install -g wrangler"
echo "     script:"
echo "       - cd frontend-modern"
echo "       - npm ci"
echo "       - npm run build"
echo "       - npx wrangler pages publish dist --project-name=ssl-monitor-pro"
echo ""

echo "🧪 Testing Current Configuration:"
echo ""
echo "1️⃣ Check API Token:"
echo "   • Token: $CLOUDFLARE_API_TOKEN"
echo "   • Account ID: $CLOUDFLARE_ACCOUNT_ID"
echo ""
echo "2️⃣ Test Wrangler Authentication:"
echo "   npx wrangler whoami"
echo ""
echo "3️⃣ Manual Deploy Test:"
echo "   cd frontend-modern"
echo "   npm run build"
echo "   npx wrangler pages publish dist --project-name=ssl-monitor-pro"
echo ""

echo "📊 Expected Results:"
echo "   • Build completes successfully"
echo "   • Files uploaded to Cloudflare Pages"
echo "   • Site accessible at https://cloudsre.xyz"
echo "   • Custom domain working"
echo ""

echo "⚠️  Important Notes:"
echo "   • Test both options before deciding"
echo "   • Option A is easier for ongoing maintenance"
echo "   • Option B gives more control"
echo "   • Keep backup of current configuration"
echo ""

echo "🔍 Verification Steps:"
echo "   1. Check current site: https://cloudsre.xyz"
echo "   2. Verify SSL certificate"
echo "   3. Test all pages load correctly"
echo "   4. Check build logs in Cloudflare"
echo ""

echo "✅ Cloudflare Pages Configuration Complete!"
echo ""
echo "📋 Next Steps:"
echo "   1. Choose integration method (A or B)"
echo "   2. Complete manual configuration"
echo "   3. Test deployment"
echo "   4. Verify custom domain"
echo "   5. Proceed to webhook verification"
echo ""
echo "🔗 Links:"
echo "   • Cloudflare Dashboard: https://dash.cloudflare.com"
echo "   • Pages Project: ssl-monitor-pro"
echo "   • Production URL: https://cloudsre.xyz"
echo "   • GitLab Variables: http://192.168.1.10/root/ssl-monitor-pro/-/settings/ci_cd"
